#!/usr/bin/env python3
"""Generate ansible/inventory/hosts.yml from Terraform outputs.

Run after `tofu apply` to sync infrastructure state into Ansible inventory.

What this does:
  - Reads public IPs and IAM Bedrock credentials from `tofu output -json`
  - Generates ansible/inventory/hosts.yml (gitignored) with per-host IPs
  - Writes per-client sensitive vars (AWS keys, gateway token) to
    ansible/host_vars/<slug>/vars.yml (gitignored)
  - Gateway tokens are generated once and preserved on subsequent runs

AWS keys: created by Terraform for each client's dedicated IAM Bedrock user.
Gateway token: a secret we generate and set in the OpenClaw env file.
  OpenClaw uses whatever token is configured — there is no pre-existing token
  to retrieve; we are defining it.

Usage:
  cd /path/to/clawless
  python3 scripts/sync-inventory.py
"""

import json
import os
import secrets
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TERRAFORM_DIR = REPO_ROOT / "terraform"
INVENTORY_FILE = REPO_ROOT / "ansible" / "inventory" / "hosts.yml"
HOST_VARS_DIR = REPO_ROOT / "ansible" / "host_vars"


def tofu_output() -> dict:
    try:
        result = subprocess.run(
            ["tofu", "output", "-json"],
            cwd=TERRAFORM_DIR,
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"Error: `tofu output` failed:\n{e.stderr}", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print("Error: `tofu` not found. Install OpenTofu first.", file=sys.stderr)
        sys.exit(1)
    return json.loads(result.stdout)


def load_vars(path: Path) -> dict:
    if not path.exists():
        return {}
    # Simple YAML key: value parser — avoids PyYAML dependency.
    data = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ": " in line:
            k, v = line.split(": ", 1)
            data[k.strip()] = v.strip().strip('"')
    return data


def write_vars(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Managed by scripts/sync-inventory.py — do not edit manually.\n"]
    for k, v in sorted(data.items()):
        lines.append(f'{k}: "{v}"\n')
    path.write_text("".join(lines))


def get_or_create_gateway_token(slug: str) -> str:
    """Return existing gateway token for this client, or generate and save a new one."""
    var_file = HOST_VARS_DIR / slug / "vars.yml"
    existing = load_vars(var_file)
    if "openclaw_gateway_token" in existing:
        return existing["openclaw_gateway_token"]
    token = secrets.token_urlsafe(32)
    print(f"  [{slug}] Generated new gateway token")
    return token


def main() -> None:
    print("Reading Terraform outputs...")
    outputs = tofu_output()

    public_ips = outputs.get("client_public_ips", {}).get("value", {})
    access_keys = outputs.get("client_iam_access_keys", {}).get("value", {})
    secret_keys = outputs.get("client_iam_secret_keys", {}).get("value", {})

    if not public_ips:
        print("No clients in Terraform state. Run `tofu apply` first.")
        sys.exit(1)

    host_entries = []
    for slug in sorted(public_ips):
        ip = public_ips[slug]
        var_file = HOST_VARS_DIR / slug / "vars.yml"

        gateway_token = get_or_create_gateway_token(slug)

        write_vars(var_file, {
            "openclaw_gateway_token":        gateway_token,
            "openclaw_aws_access_key_id":    access_keys.get(slug, ""),
            "openclaw_aws_secret_access_key": secret_keys.get(slug, ""),
        })

        host_entries.append(f"        {slug}:\n          ansible_host: {ip}\n          client_slug: {slug}")
        print(f"  [{slug}] {ip} → host_vars written")

    hosts_block = "\n".join(host_entries)
    inventory = f"""\
# Auto-generated by scripts/sync-inventory.py — do not edit manually.
---
all:
  children:
    clawless_nodes:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        openclaw_bedrock_region: us-east-1
      hosts:
{hosts_block}
"""

    INVENTORY_FILE.write_text(inventory)
    print(f"\nWrote {INVENTORY_FILE.relative_to(REPO_ROOT)}")
    print(f"Wrote ansible/host_vars/<slug>/vars.yml for {len(public_ips)} client(s)")


if __name__ == "__main__":
    main()
